### ISSUE TITLE
Publishing DSVParser-AHK as an ahkpm package?

### ISSUE THREAD

**Issue by joshuacc** [jasonsparc/DSVParser-AHK#1]
Hi @jasonsparc. I'm wondering if you'd be interested in publishing DSVParser-AHK as an ahkpm package?

ahkpm is a package manager built specifically for AutoHotkey libraries.

- Repo: https://github.com/joshuacc/ahkpm
- Docs: https://ahkpm.dev/

I've written a [guide on how to publish ahkpm packages](https://ahkpm.dev/docs/guides/publishing/) and it likely wouldn't take much time at all.

The main thing I noticed that you might need to change is to start tagging new versions with the appropriate semantic version number. e.g. `git tag 1.3.18`. 

I'd be happy to open up a PR adding the `ahkpm.json` file if you're interested.

**Comment by jasonsparc** [comment]
Done!

P.S. I must say, that stuff looks neat!

**Comment by joshuacc** [comment]
Thanks so much for doing that! DSVParser-AHK is now showing up on the [ahkpm packages page](https://ahkpm.dev/packages). :) 

![image](https://user-images.githubusercontent.com/171086/204166987-9ba5b04c-db0a-4810-94af-3cd4648c4594.png)
