### ISSUE TITLE
Any support for v2?

### ISSUE THREAD

**Issue by Cornelius-Figgle** [jasonsparc/DSVParser-AHK#2]
This project looks well developed, however it doesn't appear to have any support for AHK v2 - is this something you would consider doing?

If it helps, @mmikeww has a [converter](https://github.com/mmikeww/AHK-v2-script-converter) to take some of the load for syntax conversions etc

**Comment by jasonsparc** [comment]
I've been thinking about this for a while and was even thinking of migrating all of my personal scripts to AHK v2. I just couldn't find the time to do so. But now that you've shown me that there's an AHKv2 converter, perhaps I'll give it a try.

No promises but give me around a week and I'll try my best to release a separate v2 branch.

**Comment by Cornelius-Figgle** [comment]
sounds good, thanks for the quick reply 💪

**Comment by jasonsparc** [comment]
Hi! Sorry if I'm bit too late than what I originally alluded.

But, here's the library ported to AHK2 (in a separate repo instead): https://github.com/jasonsparc/dsvparser-ahk2

Please do check it out!

**Comment by Cornelius-Figgle** [comment]
awesome, will take a look soon :)

(also sorry if this reply is late, I thought I had replied but then couldn't find the reply so idk)
